#!/usr/bin/env bash

# Styles...

RCor="$(tput setaf 1)"
GCor="$(tput setaf 2)"
bold="$(tput bold)"
reset="$(tput sgr0)"

# Get terminal col width...

cols=$(tput cols)

# Include 'os-release' to grab Debian pretty name...

. /etc/os-release

# Extra Info
Internet=$(sed "/up\|down/!d;s/down/$RCor Offline/;s/up/$GCor Online/" /sys/class/net/*/operstate \
        | sed ':a;$!N;s/\n/ /;ta;')

# Main...

clear

echo "
$RCor ⢀⣴⠾⠻⢶⣦⠀$reset ${bold}$PRETTY_NAME${reset}
$RCor ⣾⠁⢠⠒⠀⣿⡁$reset ${bold}Kernel:${reset} $(uname -rm)
$RCor ⢿⡄⠘⠷⠚⠋⠀$reset ${bold}Uptime:${reset} $(uptime -p | cut -d' ' -f2-)
$RCor ⠈⠳⣄⠀⠀⠀⠀$reset ${bold}Status:$reset$Internet${reset}"

exit 0
