#!/usr/bin/env bash

lbc=$(wget -qO- "brl.rate.sx/lbc" \
        | grep median \
        | egrep -o '.\...' \
        | sed -e '2!d' -e 's/^/ ┃ 📚 /')

dollar=$(wget -qO- "https://dolarhoje.com" \
        | grep "value=\"" \
        | sed "s/^.*value=\"//;s/\"\/><.*$//;s/^/ ┃ 💸 /")

echo "$dollar$lbc"
