#!/usr/bin/env bash

link="$1"

program="/usr/bin/mpv"

site(){
r=$(wget -qO- "https://goyabu.com/" | \
        sed '/Lançamentos de Animes/!d' | \
        sed 's/Animes Mais Populares da Semana.*$//;s/^.*Lançamentos de Animes//' | \
        sed 's/title=\"/\n/g' | \
        sed '/class=\"clip\"/!d' | \
        sed 's/" href=\"/ ┃ /;s/\">.*$//;s/&#.*; //' | \
        fzf -e --color=16 --border |\
        sed 's/^.*┃ //')

if [ -z "$r" ] ; then
        echo -n ""
else
        $program $(wget -qO- "$r" \
                | sed '/file: \"/!d' \
                | sed 's/\"}.*$// ; s/^.*file: \"//')
fi
}

if [ -z "$link" ] ; then
        site
else
        $program $(wget -qO- "$link" \
                | sed '/file: \"/!d' \
                | sed 's/\"}.*$// ; s/^.*file: \"//')
fi
