#!/usr/bin/env bash

file=~/Update\ Mangas\ History.md
date=$(date '+%d/%m/%Y')


[ ! -f "$file" ] \
        && echo -e " | Data | Titulo | Url |\n |:-----------:|:-----------:|:--------:|" >> "$file"
 
NManga=$(grep "$date" "$file" | wc -l)

[ $NManga = 0 ] && echo "" || echo " ┃ Manga: $NManga"

download(){
        GManga=$(grep "$date" "$file" \
                | sed 's/|/\n/g;s/ //g' \
                | sed '/http/!d' \
                | sed ':a;$!N;s/\n/ /;ta;' \
                | sed 's/^/gallery-dl /')
$GManga
}

case $1 in 
        "d") download
                ;;
esac
