#!/usr/bin/env bash

#### Para este script fucionar o "flexget" e "gallery-dl" tem que esta instalado e fucionando.

File=~/Update\ Mangas\ History.md
Date=$(date '+%d/%m/%Y')
NManga=$(grep "$Date" "$File")
Download=$(echo "$NManga" | sed 's/|/\n/g;s/ //g' | sed '/http/!d' | sed ':a;$!N;s/\n/ /;ta;' | sed 's/^/gallery-dl /')

$Download
