#!/usr/bin/env bash

###############################################################################

#     _    _
#    / \  | | __ _ _ __  _ __      Alann Santos
#   / _ \ | |/ _` | '_ \| '_ \     https://github.com/alannssantos
#  / ___ \| | (_| | | | | | | |
# /_/   \_\_|\__,_|_| |_|_| |_|

OPCOES=$(lsblk -o "PATH,SIZE,FSTYPE,LABEL,RM,MOUNTPOINT" | sed -e '/sd.[0-9]/!d' -e 's/ 0 / \(Disco Local\)     /;s/ 1 / \(Disco Removível\) /')

ESCOLHA=$(echo " Escolha a Partição que deve ser Montada ou Desmontada.

$OPCOES

 Sair" | fzf -e --layout=reverse-list --color='fg:#99cc99,fg+:#2d2d2d,bg+:#99cc99,pointer:#2d2d2d,prompt:#99cc99' --margin=5% --border --no-info --phony | sed 's/ .*$//')

udisksctl mount -b $ESCOLHA $1 2> /dev/null || udisksctl unmount -b $ESCOLHA $1 2> /dev/null
