#!/usr/bin/env bash

# Script pra encontrar rss de filmes que vão ser lançados

link1='https://yts.lt/rss/'
link2=$(echo "$*" | tr ' ' '%')
link3='/all/all/0'

#program='/usr/bin/transmission-remote -n transmission:transmission -a'

program='/usr/bin/qbittorrent'

if [ -z "$link2" ] ; then
    search="0"
else
    search="$link2"
fi

final_link=${link1}${search}${link3}

r=$(wget -qO- "$final_link" \
            | grep -E '<title><!|<enclosure' \
            | sed 's/<title><!\[CDATA\[//g' \
            | sed 's/^.*url="//g' \
            | sed 's/" .*$//g' \
            | sed 's/\]\]><\/title>//g' \
            | sed 's/^ \+//' \
            | sed  'N;s!\n!|!g')

n=$(echo "$r" | wc -l)

IFS=$'\n'

echo "$r" \
	| awk -v N=1 \
		-v NU="$(tput bold)$(tput setaf 5)" \
		-v NA="$(tput bold)$(tput setaf 3)" \
		-F '|' \
		'{print NU N ") " NA $1 NO; N++}'

read -p "$(tput bold)$(tput setaf 4)>> Torrents to download: $(tput bold)$(tput setaf 2)" selection

for num in $selection ; do
 	if [ "$num" = "`echo $num | grep -o '[[:digit:]][[:digit:]]*'`" ] ; then
 		down="$down $num"
 	elif [ "$num" = "`echo $num | grep -o '[[:digit:]][[:digit:]]*-[[:digit:]][[:digit:]]*'`" ] ; then
 		seqstart="${num%-*}"
 		seqend="${num#*-}"
 		if [ $seqstart -le $seqend ] ; then
 			down="$down `seq $seqstart $seqend`"
 		fi
 	fi
done

# normalize download list, sort it and remove dupes
down="$(echo $down | tr '\ ' '\n' | sort -n | uniq)"
IFS=$'\n'


# check whether we're downloading something, else exit
if [ -z "$down" ] ; then
	exit 0
fi

# download all torrents in list
echo -n "Downloading torrent(s): "
for torrent in $down ; do
	# check if ID is valid and in range of results, download torrent
	if [ $torrent -ge 1 ] ; then
			echo -n "$torrent "
			command="$program `echo "$r" | awk -F '|' 'NR=='$torrent'{print $2; exit}'`"
			status=$(eval "$command" 2>&1)
			if [ $? -ne 0 ] ; then
				echo -n '(failed!) '
				report="$report\n(#$torrent) $status"
			fi
		fi
done
echo
if [ -n "$report" ] ; then
	echo -n "Exited with errors:"
	echo -e "$report"
fi
unset IFS
