#!/usr/bin/env bash

## Corona Virus
corona=$(wget -qO- "https://corona-stats.online" \
	| sed '/Brazil/!d;s/│/\n/g;s/ //g;s/║//g' \
	| sed '1s/^/ ┃ \(Rank: /;3s/^/\) 😷 /;5s/^/ 💀 /;7s/^/ 😄 /' \
	| sed '/ /!d' \
	| sed ':a;$!N;s/\n//;ta;')

### Coins
lbc=$(wget -qO- "brl.rate.sx/lbc" \
	| grep median \
	| grep -Eo '.\...' \
	| sed -e '2!d' -e 's/^/ ┃ 📚 /')

dollar=$(wget -qO- "https://dolarhoje.com" \
        | grep "value=\"" \
	| sed "s/^.*value=\"//;s/\"\/><.*$//;s/^/ ┃ 💸 /")
#########

echo -n "$corona"
echo -n "$dollar$lbc"
