#!/usr/bin/env bash

tmux_bar_sleep1() {
#### Update Package
Update=$(apt list --upgradable | sed '/\//!d' | wc -l)
[ "$Update" = 0 ] && echo -n "" || echo -n " #[fg=colour71]┃ #[fg=colour11]📦 Updates: $Update"
#### ━━━━━━━━━━━━━━
}

tmux_bar_inst(){
#### Transmission
Torrent=$(stig ls \
	| awk '{print $7" "$9}' \
	| sed 's/.*seeding.*\|.*uploading.*/#\[fg=colour71\] 🌱/g
		s/.*100.*/#\[fg=colour4\] ✅/g
		s/.*stopped.*/#\[fg=colour1\] 🔴/g
		s/.*connected.*\|.*idle.*\|.*discovering.*\|.*queued.*/#\[fg=colour11\] ⌛️/g
		s/.*downloading/#\[fg=colour5\] 🔽[/g;s/\..*$/%]/
		s/.*verifying/#\[fg=colour11\] ⌛️[/g;s/\..*$/%]/' \
	| sort \
	| uniq -c \
	| awk '{print $2$1$3$4}' \
	| sed ':a;$!N;s/\n/ /;ta;' \
	| sed 's/^/ #[fg=colour71]┃ /')
echo -n "$Torrent"
#### ━━━━━━━━━━━━

#### Manga Update
File=~/Update\ Mangas\ History.md
Date=$(date '+%d/%m/%Y')
[ ! -f "$File" ] && echo -e " | Data | Titulo | Url |\n |:-----------:|:-----------:|:--------:|" >> "$File"
NManga=$(grep -c "$Date" "$File")
[ "$NManga" = 0 ] && echo -n "" || echo -n " #[fg=colour71]┃ #[fg=colour4]Manga: $NManga"
#### ━━━━━━━━━━━━

#### Mpc Player
Player=$(mpc -f "[[%artist% - ]%title%]|[%file$]" 2>/dev/null \
	| grep -v 'volume:' \
	| sed -r '1!d;s/(.* )-( .*)/ #[fg=colour71]┃ 🎵 \1-#[fg=colour5]\2/')
echo -n "$Player"
#### ━━━━━━━━━━

#### Temperatura CPU
Temp=$(sensors | sed -r '/Package id 0:/!d;s/.*\+(.*)\..°C *\(.*$/ #[fg=colour71]┃ 🌡️ \1°C/')
echo -n "$Temp"
#### ━━━━━━━━━━━━━━━
}

####### Atualiza a Cada Minuto #######
if [ "$(date -r /tmp/tmux_bar_sleep1 +%M)" = "$(date '+%M')" ]; then
	cat /tmp/tmux_bar_sleep1 && tmux_bar_inst
else
	tmux_bar_sleep1 > /tmp/tmux_bar_sleep1 && cat /tmp/tmux_bar_sleep1 && tmux_bar_inst
fi
#######━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
