#!/bin/sh
# * TR_APP_VERSION
# * TR_TIME_LOCALTIME
# * TR_TORRENT_DIR
# * TR_TORRENT_HASH
# * TR_TORRENT_ID
# * TR_TORRENT_NAME
notify-send "✅ Transmission-deamon" "$TR_TORRENT_NAME Completo!"
echo "$(date '+%d/%m/%Y %H:%M:%S') $TR_TORRENT_NAME" > ~/Downloaded\ Torrent\ History.log
