#!/usr/bin/env bash
#
# ufetch-ubuntu - tiny system info for ubuntu

## INFO

. /etc/os-release

# user is already defined
host="$(hostname)"
os="$VERSION"
kernel="$(uname -sr)"
uptime="$(uptime -p | sed 's/up //')"
packages="$(dpkg -l | wc -l)"
shell="$(basename "$SHELL")"
memory="$(free -mh | grep Mem | awk '{print $3;}') / $(free -mh | grep Mem | awk '{print $2;}')"

## UI DETECTION

if [ -n "${DE}" ]; then
	ui="${DE}"
	uitype='DE'
elif [ -n "${WM}" ]; then
	ui="${WM}"
	uitype='WM'
elif [ -n "${XDG_CURRENT_DESKTOP}" ]; then
	ui="${XDG_CURRENT_DESKTOP}"
	uitype='DE'
elif [ -n "${DESKTOP_SESSION}" ]; then
	ui="${DESKTOP_SESSION}"
	uitype='DE'
elif [ -f "${HOME}/.xinitrc" ]; then
	ui="$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)"
	uitype='WM'
elif [ -f "${HOME}/.xsession" ]; then
	ui="$(tail -n 1 "${HOME}/.xsession" | cut -d ' ' -f 2)"
	uitype='WM'
else
	ui='unknown'
	uitype='UI'
fi

## DEFINE COLORS

# probably don't change these
if [ -x "$(command -v tput)" ]; then
	bold="$(tput bold)"
	black="$(tput setaf 0)"
	red="$(tput setaf 1)"
	green="$(tput setaf 2)"
	yellow="$(tput setaf 3)"
	blue="$(tput setaf 4)"
	magenta="$(tput setaf 5)"
	cyan="$(tput setaf 6)"
	white="$(tput setaf 7)"
	reset="$(tput sgr0)"
fi

# you can change these
lc="${reset}${bold}${white}"       # labels
nc="${reset}${bold}${green}"       # user and hostname
ic="${reset}"                       # info
c0="${reset}${cyan}"              # first color
w0="${reset}${white}"
r0="${reset}${red}"
m0="${reset}${magenta}"
b0="${reset}${blue}"
y0="${reset}${yellow}"
g0="${reset}${green}"

## OUTPUT

# cat <<EOF

# ${c0} ⠀⠀⣀⣴⣾⣿⣿⣿⣿⣷⣦⣀⠀⠀  ${nc}${USER}${ic}@${nc}${host}${reset}
# ${c0} ⢀⣼⣿⠋⠀⣄⠀⠹⣿⣿⣿⣿⣧⡀  ${lc}OS:        ${ic}${os}${reset}
# ${c0} ⣾⣿⣿⣆⠀⠿⠇⢠⣿⠉⢙⣿⣿⣷  ${lc}KERNEL:    ${ic}${kernel}${reset} 
# ${c0} ⣿⣿⣿⣿⣆⠀⢶⣿⣿⢀⣾⣿⣿⣿  ${lc}UPTIME:    ${ic}${uptime}${reset}
# ${c0} ⢿⣿⣿⣿⣿⣆⡘⣿⡟⣾⣿⣿⣿⡿  ${lc}PACKAGES:  ${ic}$(dpkg -l | wc -l)${reset} 
# ${c0} ⠈⢻⣿⡟⠛⠛⠛⠛⠛⠛⢻⣿⡟⠁  ${lc}SHELL:     ${ic}${shell}${reset}
# ${c0} ⠀⠀⠉⠻⢿⣿⣿⣿⣿⡿⠟⠉⠀⠀  ${lc}${uitype}:        ${ic}${ui}${reset}

# EOF

cat <<EOF

${y0} ⠀⠀⣀⣴⣾⣿⣿⣿⣿⣷⣦⣀⠀⠀  ${nc}${USER}${ic}@${nc}${host}${reset}
${y0} ⢀⣼⣿⣿⣿⡟⠛⠛⢯⣀⣽⣿⣧⡀  ${lc}OS:        ${ic}${os}${reset}
${y0} ⣾⣿⣿⠏⢀⣿⣿⣿⣮⡉⠹⣿⣿⣷  ${lc}KERNEL:    ${ic}${kernel}${reset} 
${y0} ⣿⣏⢈⡇⢾⣿⣿⣿⣿⡷⠶⣿⣿⣿  ${lc}UPTIME:    ${ic}${uptime}${reset}
${y0} ⢿⣿⣿⣆⠈⣿⢿⡿⢟⣁⣰⣿⣿⡿  ${lc}PACKAGES:  ${ic}$(dpkg -l | wc -l)${reset} 
${y0} ⠈⢻⣿⣿⣿⣧⣤⣤⣎⠉⣻⣿⡟⠁  ${lc}SHELL:     ${ic}${shell}${reset}
${y0} ⠀⠀⠉⠻⢿⣿⣿⣿⣿⡿⠟⠉⠀⠀  ${lc}MEMORY:    ${ic}$memory${reset}

EOF

# cat <<EOF

# ${r0}   ⠀⢀⣤⣶⠿⠷⠶⣴⣄⠀    ${nc}${USER}${ic}@${nc}${host}${reset}
# ${r0}   ⢀⡾⠋⠀⠀⠀⠀⠈⢻⣧    ${lc}OS:        ${ic}${os}${reset}
# ${r0}   ⣾⠁⠀⠀⠌⠁⠈⠀⠈⡇    ${lc}KERNEL:    ${ic}${kernel}${reset} 
# ${r0}   ⣏⠀⠀⢀⡆⠀⠀⠂⣸⠃    ${lc}UPTIME:    ${ic}${uptime}${reset}
# ${r0}   ⢻⡄⠀⠀⠙⠲⠒⠊⠁⠀    ${lc}PACKAGES:  ${ic}$(dpkg -l | wc -l)${reset} 
# ${r0}   ⠈⢻⡀⠀⠀⠀⠀⠀⠀⠀    ${lc}SHELL:     ${ic}${shell}${reset}
# ${r0}   ⠀⠀⠙⠦⣀⠀⠀⠀⠀⠀    ${lc}${uitype}:        ${ic}${ui}${reset}

# EOF

# cat <<EOF

# ${b0} ⠀⠀⠀⠀⠀⠀⣰⡄⠀⠀⠀⠀⠀⠀  ${nc}${USER}${ic}@${nc}${host}${reset}
# ${b0} ⠀⠀⠀⠀⠀⢠⣿⣿⡄⠀⠀⠀⠀⠀  ${lc}OS:        ${ic}Arch Linux${reset}
# ${b0} ⠀⠀⠀⠀⢠⣮⣿⣿⣿⡄⠀⠀⠀⠀  ${lc}KERNEL:    ${ic}${kernel}${reset} 
# ${b0} ⠀⠀⠀⢠⣿⣿⣿⣿⣿⣿⡄⠀⠀⠀  ${lc}UPTIME:    ${ic}${uptime}${reset}
# ${b0} ⠀⠀⢠⣿⣿⡟⠁⠈⢻⣿⣿⡄⠀⠀  ${lc}PACKAGES:  ${ic}$(pacman -Q | wc -l)${reset} 
# ${b0} ⠀⣰⣿⣿⡿⠇⠀⠀⠸⢿⣷⣯⡀⠀  ${lc}SHELL:     ${ic}${shell}${reset}
# ${b0} ⠰⠛⠉⠀⠀⠀⠀⠀⠀⠀⠈⠉⠛⢆  ${lc}${uitype}:        ${ic}${ui}${reset}

# EOF

# cat <<EOF

# ${b0}⠀⠀⠀⠀⠀⠀⠀⣸⣆⠀⠀⠀⠀⠀⠀ ⠀${nc}${USER}${ic}@${nc}${host}${reset}
# ${b0}⠀⠀⠀⠀⠀⠀⣰⣿⣿⣆⠀⠀⠀⠀⠀ ⠀${lc}OS:        ${ic}ArcoLinux${reset}
# ${b0}⠀⠀⠀⠀⠀⣰⣿⣿⣿⣿⣆⠀⠀⠀⠀ ⠀${lc}KERNEL:    ${ic}${kernel}${reset} 
# ${b0}⠀⠀⠀⠀⣰⣿⣿⠃⠹⣿⣿⡄⠀⠀⠀ ⠀${lc}UPTIME:    ${ic}${uptime}${reset}
# ${b0}⠀⠀⠀⢰⣿⣿⠃⠀⠀⠹⣿⣿⡄⠀⠀ ⠀${lc}PACKAGES:  ${ic}$(pacman -Q | wc -l)${reset} 
# ${b0}⠀⠀⢠⣿⣿⠃⠀⠒⠲⢶⣿⣿⣿⡄⠀ ⠀${lc}SHELL:     ${ic}${shell}${reset}
# ${b0}⠀⠠⠿⠿⠃⠀⠀⠀⠀⠀⠉⠻⣿⣿⡀ ⠀${lc}${uitype}:        ${ic}${ui}${reset}

# EOF

# cat <<EOF

# ${g0} ⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⣿⣿⣿⣿  ${nc}${USER}${ic}@${nc}${host}${reset}
# ${g0} ⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⣿⣿⣿⣿  ${lc}OS:        ${ic}Manjaro${reset}
# ${g0} ⣿⣿⣿⣿⠀⣤⣤⣤⣤⠀⣿⣿⣿⣿  ${lc}KERNEL:    ${ic}${kernel}${reset} 
# ${g0} ⣿⣿⣿⣿⠀⣿⣿⣿⣿⠀⣿⣿⣿⣿  ${lc}UPTIME:    ${ic}${uptime}${reset}
# ${g0} ⣿⣿⣿⣿⠀⣿⣿⣿⣿⠀⣿⣿⣿⣿  ${lc}PACKAGES:  ${ic}$(pacman -Q | wc -l)${reset} 
# ${g0} ⣿⣿⣿⣿⠀⣿⣿⣿⣿⠀⣿⣿⣿⣿  ${lc}SHELL:     ${ic}${shell}${reset}
# ${g0} ⣿⣿⣿⣿⠀⣿⣿⣿⣿⠀⣿⣿⣿⣿  ${lc}${uitype}:        ${ic}${ui}${reset}

# EOF

# cat <<EOF

# ${y0}⠀⠀⠀⠀⠀⠀⠀⢴⡦⠀⠀⠀⠀⠀   ${nc}${USER}${ic}@${nc}${host}${reset}    ⠀⠀⠀⠀⠀⠀
# ${g0}⠀⠀⠀⣿⢟⢵⣿${y0}⢸⡇${m0}⣿⡮⡻⣿   ⠀${lc}OS:        ${ic}$(cat /etc/centos-release | sed 's/release //')${reset}        ⠀⠀⠀⠀⠀⠀
# ${g0}⠀⠀⠀⣵⣷⣕⢝${y0}⢸⡇${m0}⡫⣪⣾⣮   ⠀${lc}KERNEL:    ${ic}${kernel}${reset}    ⠀⠀⠀⠀⠀⠀
# ${m0}⠀⠰⡷⣶⣶⣶⡶${b0}⠀⠀⠶⣶⣶⣶⢾⠆⠀⠀${lc}UPTIME:    ${ic}${uptime}${reset}    ⠀
# ${b0}⠀⠀⠀⡻⡿⡫⣪${g0}⢸⡇${y0}⣕⢝⢿⢟   ⠀${lc}PACKAGES:  ${ic}$(yum list installed | wc -l)${reset}  ⠀⠀⠀⠀⠀⠀
# ${b0}⠀⠀⠀⣿⣮⡺⣿${g0}⢸⡇${y0}⣿⢗⣵⣿   ⠀${lc}SHELL:     ${ic}${shell}${reset}     ⠀⠀⠀⠀⠀⠀
# ${g0}⠀⠀⠀⠀⠀⠀⠈⠻⠟⠁⠀⠀⠀⠀⠀  ${lc}${uitype}:        ${ic}${ui}${reset}

# EOF

# cat <<EOF

# ${m0}⠀⠀⠀⢀⣤⣶⣿⣿⣿⣿⣶⣦⡀⠀⠀⠀⠀${nc}${USER}${ic}@${nc}${host}${reset}
# ${m0}⠀⠀⣴⣿⣿⠛⠀⢀⣈⠙⠛⣿⣿⣦⠀⠀⠀${lc}OS:        ${ic}Gentoo Linux${reset}        ⠀⠀⠀
# ${m0}⠀⣸⣿⣿⡗⢄⡀⠘⠦⠃⠀⠘⡿⣿⣇⠀⠀${lc}KERNEL:    ${ic}${kernel}${reset}    ⠀⠀⠀
# ${m0}⠀⣿⣿⣿⣿⠷⠊⠀⠀⠀⢀⠔⣱⣿⣿⠀⠀${lc}UPTIME:    ${ic}${uptime}${reset}    ⠀⠀⠀
# ${m0} ⢸⣿⣿⢋⠀⠀⣀⡤⢒⣥⣾⣿⣿⡇⠀⠀${lc}PACKAGES:  ${ic}$(ls -d /var/db/pkg/*/* | wc -l)${reset}  ⠀⠀⠀
# ${m0}⠀⠀⠛⣿⣯⣭⣭⣴⣾⣿⣿⣿⣿⠟⠀⠀⠀${lc}SHELL:     ${ic}${shell}${reset}     ⠀⠀⠀
# ${m0}⠀⠀⠀⠀⠙⠻⢿⣿⣿⡿⠟⠋⠀⠀⠀⠀⠀${lc}${uitype}:        ${ic}${ui}${reset} ⠀⠀⠀

# EOF

# cat <<EOF

# ${b0}⠀⠀⠀⠀⢀⣠⡴⠶⠶⠶⢦⣄⡀⠀⠀⠀⠀${nc}${USER}${ic}@${nc}${host}${reset}
# ${b0}⠀⠀⠀⣰⢟⣥⠞⣫⣭⣝⢷⣬⡻⣦⠀⠀⠀${lc}OS:        ${ic}${os}${reset}
# ${b0}⠀⠀⣰⢇⣾⠏⣾⣿⣿⣿⢸⣿⣷⠸⣇⠀⠀${lc}KERNEL:    ${ic}${kernel}${reset} 
# ${b0}⠀⠀⣿⢸⣿⢸⣿⣿⡿⣣⣿⣿⢏⡄⣿⠀⠀${lc}UPTIME:    ${ic}${uptime}${reset}
# ${b0}⠀⠀⠹⡎⠿⠆⠙⠩⠾⠿⢛⣵⡿⢱⡏⠀⠀${lc}PACKAGES:  ${ic}$(dpkg -l | wc -l)${reset} 
# ${b0}⠀⠀⠀⠹⣦⡛⢿⣷⣶⣿⡿⢛⣵⠟⠀⠀⠀${lc}SHELL:     ${ic}${shell}${reset}
# ${b0}⠀⠀⠀⠀⠈⠙⠳⠶⠶⠶⠞⠋⠁⠀⠀⠀⠀${lc}${uitype}:        ${ic}${ui}${reset}

# EOF

# cat <<EOF

# ${g0}⠀⠀⣀⣀⣀⣀⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀${nc}${USER}${ic}@${nc}${host}${reset}    ⠀⠀
# ${g0}⠀⠀⣿⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠶⣄⠀⠀⠀${lc}OS:        ${ic}${os}${reset}        ⠀⠀
# ${g0}⠀⠀⠿⠤⡄⠀⣿⠀⢀⣤⣄⣠⣤⣀⠹⣧⠀⠀${lc}KERNEL:    ${ic}${kernel}${reset}    ⠀⠀
# ${g0}⠀⠀⠀⠀⡇⠀⣿⠀⣿⠁⢹⡏⠈⣿⠀⣿⠀⠀${lc}UPTIME:    ${ic}${uptime}${reset}    ⠀⠀
# ${g0}⠀⠀⠀⠀⡇⠀⣿⠀⠿⠀⠸⠇⠀⣿⠀⣿⠀⠀${lc}PACKAGES:  ${ic}$(dpkg -l | wc -l)${reset}  ⠀⠀
# ${g0}⠀⠀⠀⠀⣷⡀⠻⣦⣤⣤⣤⣤⡴⠟⠀⣿⠀⠀${lc}SHELL:     ${ic}${shell}${reset}     ⠀⠀
# ${g0}⠀⠀⠀⠀⠈⠻⢦⣤⣤⣤⣤⣤⣤⣤⣤⣿⠀⠀${lc}${uitype}:        ${ic}${ui}${reset} ⠀⠀

# EOF

# cat <<EOF

# ${w0}  ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿  ${nc}${USER}${ic}@${nc}${host}${reset}   
# ${w0}  ⣿⣿⣿⠟⠻⣿⣿⣿⣿⣿⣿⠛⢿⣿  ${lc}OS:        ${ic}${os}${reset}       
# ${w0}  ⣿⣿⣿⣄⠀⠙⢿⣿⣿⠟⠁⣴⣿⣿  ${lc}KERNEL:    ${ic}${kernel}${reset}   
# ${w0}  ⣿⣿⣿⣿⣷⡀⠀⠙⠃⣠⣾⣿⣿⣿  ${lc}UPTIME:    ${ic}${uptime}${reset}   
# ${w0}  ⣿⣿⣿⡿⠛⠿⠂⠀⠈⠻⣿⣿⣿⣿  ${lc}PACKAGES:  ${ic}$(dpkg -l | wc -l)${reset} 
# ${w0}  ⣿⣿⠟⠀⠀⠀⠰⣷⣄⠀⠘⠿⣿⣿  ${lc}SHELL:     ${ic}${shell}${reset}    
# ${w0}  ⡟⠁⠀⠀⠀⠀⠀⠈⠻⡷⠀⠀⠈⢿  ${lc}${uitype}:        ${ic}${ui}${reset}

# EOF

# cat <<EOF

# ${g0}  ⠀⠀⠀⣀⣤⣤⣤⣤⣀⠀⠀⠀⠀  ⠀${nc}${USER}${ic}@${nc}${host}${reset}   
# ${g0}  ⠀⠰⠏⠛⠛⠛⠿⢿⣿⣿⣦⠀⠀  ⠀${lc}OS:        ${ic}${os}${reset}       
# ${g0}  ⠀⠀⠀⠀⠀⢀⠔⣒⢬⠹⣿⣧⠀  ⠀${lc}KERNEL:    ${ic}${kernel}${reset}   
# ${g0}  ⠀⠀⠀⠠⣀⠘⢄⣈⠼⠀⢻⣿⠀  ⠀${lc}UPTIME:    ${ic}${uptime}${reset}   
# ${g0}  ⠀⠀⠀⠀⠉⠑⠒⠤⠤⠒⣽⡟⠀  ⠀${lc}PACKAGES:  ${ic}$(rpm -qa --last | wc -l)${reset} 
# ${g0}  ⠀⠠⣤⣤⣤⣤⣤⣤⣶⣿⠟⠀⠀  ⠀${lc}SHELL:     ${ic}${shell}${reset}    
# ${g0}  ⠀⠀⠀⠉⠛⠛⠛⠛⠉⠀⠀⠀⠀  ⠀${lc}${uitype}:        ${ic}${ui}${reset}

# EOF

# cat <<EOF

# ${c0}    ⠀⠀⠀⠀⠤⢀⠀⠀⠀⠀⠀  ⠀${nc}${USER}${ic}@${nc}${host}${reset}   
# ${c0}    ⠀⠀⠀⠀⠰⠎⠁⠀⠀⠀⠀  ⠀${lc}OS:        ${ic}${os}${reset}       
# ${c0}    ⠀⠀⠀⠰⠗⠘⠃⠀⠀⠀⠀  ⠀${lc}KERNEL:    ${ic}${kernel}${reset}   
# ${b0}    ⠀⢠⠟⠲⠶⠶⠖⠻⡄⠀⠀  ⠀${lc}UPTIME:    ${ic}${uptime}${reset}   
# ${b0}    ⠀⣿⠀⠀⠀⠀⠀⠀⣿⠀⠀  ⠀${lc}PACKAGES:  ${ic}$(yum list installed | wc -l)${reset} 
# ${b0}    ⠀⠘⣦⡀⠀⠀⠀⣰⠃⠀⠀  ⠀${lc}SHELL:     ${ic}${shell}${reset}    
# ${b0}    ⠀⠀⠈⠙⠓⠚⠋⠁⠀⠀⠀  ⠀${lc}${uitype}:        ${ic}${ui}${reset}

# EOF

# cat <<EOF

# ${b0}  ⠀⠀⠀⠀⠀⠀⣰⣆⠀⠀⠀⠀⠀⠀  ${nc}${USER}${ic}@${nc}${host}${reset}   
# ${b0}  ⠀⠀⠀⠀⠀⣰⣿⣿⣆⠀⠀⠀⠀⠀  ${lc}OS:        ${ic}Artix Linux${reset}       
# ${b0}  ⠀⠀⠀⠀⠐⠿⣿⣿⣿⣆⠀⠀⠀⠀  ${lc}KERNEL:    ${ic}${kernel}${reset}   
# ${b0}  ⠀⠀⠀⣰⣶⣤⣀⠉⠻⢿⣆⠀⠀⠀  ${lc}UPTIME:    ${ic}${uptime}${reset}   
# ${b0}  ⠀⠀⣰⣿⣿⣿⣿⣿⣷⣦⡬⠀⠀⠀  ${lc}PACKAGES:  ${ic}$(pacman -Q | wc -l)${reset} 
# ${b0}  ⠀⣰⣿⣿⣿⡿⠿⠛⠉⣁⣴⣾⣆⠀  ${lc}SHELL:     ${ic}${shell}${reset}    
# ${b0}  ⣰⠿⠛⠋⠁⠀⠀⠀⠈⠉⠛⠻⢿⣆  ${lc}${uitype}:        ${ic}${ui}${reset}

# EOF

# cat <<EOF

# ${r0}  ⠀⠀⣀⣴⣶⣿⣿⣿⣿⣶⣦⣀⠀⠀  ${nc}${USER}${ic}@${nc}${host}${reset}
# ${r0}  ⢀⣼⡟⠛⡿⠿⠛⠛⢿⡿⠛⢻⣧⡀  ${lc}OS:        ${ic}$(uname -sr)${reset}
# ${r0}  ⣼⣿⣷⠎⠀⠀⠀⠀⠱⣀⢠⣾⣿⣧  ${lc}KERNEL:    ${ic}$(uname -iK)${reset} 
# ${r0}  ⣿⣿⡏⠀⠀⠀⠀⠀⠀⠀⠉⢸⣿⣿  ${lc}UPTIME:    ${ic}$(uptime | awk -F, '{sub(".*up ",x,$1);print $1}' | sed -e 's/^[ \t]*//')${reset}
# ${r0}  ⢻⣿⣷⡀⠀⠀⠀⠀⠀⠀⠀⣼⣿⡟  ${lc}PACKAGES:  ${ic}$(pkg info | wc -l | sed -e 's/^[ \t]*//')${reset} 
# ${r0}  ⠈⢻⣿⣷⣄⣀⠀⠀⢀⣠⣾⣿⡟⠁  ${lc}SHELL:     ${ic}${shell}${reset}
# ${r0}  ⠀⠀⠉⠻⠿⣿⣿⣿⣿⠿⠟⠉⠀⠀  ${lc}${uitype}:        ${ic}${ui}${reset}

# EOF

# cat <<EOF

# ${b0}  ⠀⠀⢀⣤⣶⣿⣿⣿⡿⢶⣤⡀⠀⠀  ${nc}${USER}${ic}@${nc}${host}${reset}
# ${b0}  ⠀⣴⣿⣿⣿⣿⠋⠀⣠⣤⣼⣿⣦⠀  ${lc}OS:        ${ic}$(cat /etc/fedora-release)${reset}
# ${b0}  ⣼⣿⣿⣿⣿⣿⠀⢸⣿⣿⣿⣿⣿⣧  ${lc}KERNEL:    ${ic}${kernel}${reset} 
# ${b0}  ⣿⣿⣿⡟⠉⠉⠀⠈⠉⢻⣿⣿⣿⣿  ${lc}UPTIME:    ${ic}${uptime}${reset}
# ${b0}  ⣿⣿⣿⣿⣿⣷⠀⢸⣿⣿⣿⣿⣿⡟  ${lc}PACKAGES:  ${ic}$(yum list installed | wc -l)${reset} 
# ${b0}  ⣿⣿⣿⠿⠿⠋⠀⣾⣿⣿⣿⣿⠟⠀  ${lc}SHELL:     ${ic}${shell}${reset}
# ${b0}  ⢿⣿⣧⣤⣤⣤⣾⣿⣿⠿⠛⠁⠀⠀  ${lc}${uitype}:        ${ic}${ui}${reset} ⠀

# EOF

# cat <<EOF

# ${b0} ⠀⠀⢀⣤⣶⣿⣿⣿⣷⣶⣤⡀⠀⠀   ${nc}${USER}${ic}@${nc}${host}${reset}
# ${b0} ⠀⣴⣿⣿⡟⢉⣉⣉⠉⢹⣿⣿⣦⠀   ${lc}OS:        ${ic}$(cat /etc/slackware-version)${reset}
# ${b0} ⣸⣿⣿⣿⣆⠘⠛⠛⠓⢾⣿⣿⣿⣧   ${lc}KERNEL:    ${ic}${kernel}${reset} 
# ${b0} ⣿⣿⣿⣿⠋⠻⣿⣿⡷⠀⣿⣿⣿⣿   ${lc}UPTIME:    ${ic}${uptime}${reset}
# ${b0} ⢻⣿⢹⣿⣦⣦⣤⣤⣴⣾⣿⣿⣿⡟   ${lc}PACKAGES:  ${ic}$(ls /var/log/packages | wc -l)${reset} 
# ${b0} ⠀⠻⣬⣭⣭⣭⣭⣭⣭⣭⣭⣭⠟⠀   ${lc}SHELL:     ${ic}${shell}${reset}
# ${b0} ⠀⠀⠈⠛⠿⣿⣿⣿⣿⠿⠛⠁⠀⠀   ${lc}${uitype}:        ${ic}${ui}${reset}

# EOF

# cat <<EOF

# ${g0}⠀⠀⠀⠀⠀⠀⠠⣶⣿⣿⣿⣿⣿⣷⣤⡀⠀⠀   ⠀${nc}${USER}${ic}@${nc}${host}${reset}    ⠀⠀⠀⠀
# ${g0}⠀⠀⠀⠀⢠⣦⡀⠈⠋⠉⠀⠈⠉⠻⣿⣿⣆⠀⠀⠀ ⠀${lc}OS:        ${ic}Void Linux${reset}        ⠀⠀
# ${w0}⠀⢠⣤⣄${g0}⣿⣿⠏${w0}⡠⢄⣴⣶⣶⣄⢠⣼⣟⣿⣦⣤⣤ ⠀${lc}KERNEL:    ${ic}${kernel}${reset}    ⠀⠀
# ${w0}⠀⠀⠻⣿⡾⣷⡉⢰⣿⣟⣠⣿⣟⣿⣟⣾⡿⢇⣾⡿ ⠀${lc}UPTIME:    ${ic}${uptime}${reset}    ⠀⠀
# ${w0}⠀⠀⠀⠉${g0}⢿⣿⣧⡀${w0}⠉⠙⠛⠋⠉⠉${g0}⠸⣿⣿⠉⠁⠀ ⠀${lc}PACKAGES:  ${ic}$(xbps-query -l | wc -l)${reset}  ⠀⠀
# ${g0}⠀⠀⠀⠀⠈⠻⣿⣿⣶⣤⣤⣤⣴⣦⡀⠈⠁⠀⠀⠀ ⠀${lc}SHELL:     ${ic}${shell}${reset}     ⠀⠀
# ${g0}⠀⠀⠀⠀⠀⠀⠈⠙⠻⠿⠿⠿⠟⠛⠁⠀⠀⠀⠀⠀ ⠀${lc}${uitype}:        ${ic}${ui}${reset} ⠀⠀

# EOF

# cat <<EOF

# ${y0} ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡀⠀⢠⠀⠀⡄⠀⠀⠀⠀⠀  ${nc}${USER}${ic}@${nc}${host}${reset}
# ${y0} ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠠⡀⠀⣷⡀⠿⠀⣾⠃⢀⡀⠀⠀⠀  ${lc}OS:        ${ic}${os}${reset}
# ${y0} ⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠀⠹⠖⠀⠀⠀⠀⠀⠘⠟⣀⣀⠄⠀  ${lc}KERNEL:    ${ic}${kernel}${reset} 
# ${y0} ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⠇⠀⠀⠀⠀⠀⠀⠀⠀⠟⠉⠀⠀  ${lc}UPTIME:    ${ic}${uptime}${reset}
# ${b0} ⢠⠖⠲⠀⣴⠖⢶⡄⢰⡆⠀⠴⠒⢶⡀⢰⣦⠖⢰⡆⢠⡖⠲⠀  ${lc}PACKAGES:  ${ic}${packages}${reset} 
# ${b0} ⠘⠳⣦⠀⣏⠀⢸⡇⢸⡇⠀⣤⠖⢺⡇⢸⡇⠀⢸⡇⠘⠳⣦⡀  ${lc}SHELL:     ${ic}${shell}${reset}
# ${b0} ⠠⠤⠞⠀⠻⠤⠾⠁⠸⠧⠄⠿⠤⠺⠇⠸⠇⠀⠸⠇⠠⠤⠾⠁  ${lc}${uitype}:        ${ic}${ui}${reset}

# EOF
