#!/usr/bin/env bash

#     _    _
#    / \  | | __ _ _ __  _ __      Alann Santos
#   / _ \ | |/ _` | '_ \| '_ \     https://gitlab.com/alannssantos
#  / ___ \| | (_| | | | | | | |
# /_/   \_\_|\__,_|_| |_|_| |_|

## Cores.
RCor="\033[1;31m"    # Red (Vermelho)
GCor="\033[1;32m"    # Green (Verde)
YCor="\033[1;33m"    # Yellow (Amarelo)
BCor="\033[1;34m"    # Blue (Azul)
WCor="\033[1;37m"    # White (Branco)
ECor="\033[0m"       # End (Fim)

## Mensagens

Sussesso="$YCor
╭────────────────────────╮
│$GCor Instalado com sucesso!$YCor │
╰────────────────────────╯
$ECor"
Fracasso="$YCor
╭────────────────────────╮
│  $RCor Erro na instalação!$YCor  │
╰────────────────────────╯
$ECor"

Menu(){
echo -e "$BCor
    1.Sistema
    2.Bat e Google Chrome
    3.Fuzzy Finder e Vim-plug
    4.Nerd Fonts e Ranger config $YCor(pode demorar bastante tempo.)$BCor
    5.Configs
$ECor"
read -r Resposta

case "$Resposta" in
    1)
        #### Aplicativos e Drivers Pos-instalação.
        sudo apt install gparted \
		libjpeg62-turbo-dev \
		zlib1g-dev \
		python3-dev \
		libxtst-dev \
		curl \
		slop \
		lynx \
		fonts-firacode \
		sxiv \
		redshift \
		aptitude \
		alsa-utils \
		mpv \
		compton \
		atool \
		python3-pip \
		mpg123 \
		pavucontrol \
		neovim \
		zathura \
		rar \
		ffmpegthumbnailer \
		w3m-img \
		neomutt \
		streamlink \
		irssi \
		peek \
		youtube-dl \
		simple-scan \
		numix-gtk-theme \
                numix-icon-theme \
                numix-icon-theme-circle \
		ttf-mscorefonts-installer \
		papirus-icon-theme \
		arc-theme \
		breeze-cursor-theme \
		blueman \
		keepassxc \
		tmux \
		smplayer \
		xdotool \
		transmission-gtk \
		xfce4-terminal \
		python3-libtorrent -y && \
#
	sudo apt update && \
	sudo apt upgrade -y && \
	sudo -H pip3 install ranger-fm && \
	sudo -H pip3 install youtube-dl --upgrade && \
	sudo -H pip3 install subliminal --upgrade && \
        sudo -H pip3 install flexget==3.1.50 && \
	sudo -H pip3 install ueberzug && \
	pip3 install transmissionrpc && \
	pip3 install gallery-dl && \
	echo -e "$BCor\n01.Sistema!$ECor" && \
        echo -e "$Sussesso" || \
        echo -e "$Fracasso"
        Menu ;;
    2)
        #### Bat (cat mais bonito.)
        url1="https://github.com"
        url2=$(wget -qO- "https://github.com/sharkdp/bat/releases" \
            | grep "<a href=" \
            | grep "bat_" \
            | grep "_amd64.deb" \
            | sed '1!d' \
            | sed 's/^.*href="//' \
            | sed 's/" rel=.*$//')
        wget -c "$url1$url2" && \
        sudo dpkg -i bat_*_amd64.deb && \
        echo -e "$BCor\n02.Instalacao do Bat!$ECor" && \
        echo -e "$Sussesso" || \
        echo -e "$Fracasso"

        #### Google Chrome.
        wget -c https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
        sudo dpkg -i google-chrome-stable_current_amd64.deb && \
        sudo apt install -f && \
        echo -e "$BCor\n02.Google Chrome.$ECor" && \
        echo -e "$Sussesso" || \
        echo -e "$Fracasso"
        Menu ;;

    3)
        #### Instalação do Fuzzy Finder e Vim-plug.
        git clone --depth 1 https://github.com/junegunn/fzf.git ~/.config/fzf && ~/.config/fzf/install --all && \
        sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
        echo -e "$BCor\n03.Instalacao do Fuzzy Finder e Vim-plug$ECor" && \
        echo -e "$Sussesso" || \
        echo -e "$Fracasso"
        Menu ;;

    4)
        #### Nerd Fonts e Ranger config.
        git clone https://github.com/ryanoasis/nerd-fonts.git && cd nerd-fonts && ./install.sh && \
        git clone https://github.com/alexanderjeurissen/ranger_devicons ~/.config/ranger/plugins/ranger_devicons && cd ~/.config/ranger/plugins/ranger_devicons && make install && \
        echo -e "$BCor\n04.Nerd Fonts e Ranger config.$ECor" && \
        echo -e "$Sussesso" || \
        echo -e "$Fracasso"
        Menu ;;
    5)
        #### Copiar Dotfiles e Plugins.
        cp -r -v .config .irssi .bash_aliases .nanorc .tmux.conf .Xresources ~/ && \
        echo -e "$BCor\n05.Copiando arquivos de configuração...$ECor" && \
        echo -e "$Sussesso" || \
        echo -e "$Fracasso"
        Menu ;;
    q)
        exit ;;
    *)
        clear
        echo -e "$YCor

        ╭────────────────────────╮
        │$RCor   Opção desconhecida.$YCor  │
        ╰────────────────────────╯
            $ECor"
        Menu ;;
esac
}
Menu
