tasks:
# Remove torrent depois de Upar o dobro!
  clean-transmission:
    disable: [seen, seen_info_hash]
    accept_all: yes
    from_transmission:
      only_complete: yes
    if:
      - transmission_ratio < 1.0: reject
    transmission:
      action: remove
# RSS
  Mangas:
    sequence:
      - rss: https://mangadex.org/rss/gvKM3hsdH9pe6AwZC8RQqarbNnutykYX/manga_id/22151
      - rss: https://mangadex.org/rss/gvKM3hsdH9pe6AwZC8RQqarbNnutykYX/manga_id/22631
      - rss: https://mangadex.org/rss/gvKM3hsdH9pe6AwZC8RQqarbNnutykYX/manga_id/20882
      - rss: https://mangadex.org/rss/gvKM3hsdH9pe6AwZC8RQqarbNnutykYX/manga_id/17910
      - rss: https://mangadex.org/rss/gvKM3hsdH9pe6AwZC8RQqarbNnutykYX/manga_id/12714
      - rss: https://mangadex.org/rss/gvKM3hsdH9pe6AwZC8RQqarbNnutykYX/manga_id/35439
      - rss: https://mangadex.org/rss/gvKM3hsdH9pe6AwZC8RQqarbNnutykYX/manga_id/16411
      - rss: https://mangadex.org/rss/gvKM3hsdH9pe6AwZC8RQqarbNnutykYX/manga_id/16588
      - rss: https://mangadex.org/rss/gvKM3hsdH9pe6AwZC8RQqarbNnutykYX/manga_id/21048
      - rss: https://mangadex.org/rss/gvKM3hsdH9pe6AwZC8RQqarbNnutykYX/manga_id/15016
      - rss: https://mangadex.org/rss/gvKM3hsdH9pe6AwZC8RQqarbNnutykYX/manga_id/16099
      - rss: https://mangadex.org/rss/gvKM3hsdH9pe6AwZC8RQqarbNnutykYX/manga_id/21040
      - rss: https://mangadex.org/rss/gvKM3hsdH9pe6AwZC8RQqarbNnutykYX/manga_id/32386
      - rss: https://mangadex.org/rss/gvKM3hsdH9pe6AwZC8RQqarbNnutykYX/manga_id/24249
    regexp:
      accept:
        - (English)
    exec: echo " | $(date '+%d/%m/%Y %H:%M:%S') | {{title}} | {{url}} |" >> ~/Update\ Mangas\ History.md
  Animes:
    sequence:
      - rss: https://nyaa.si/?page=rss&q=Tower+of+God&c=1_2&f=2
    regexp:
      accept:
        - (\[HorribleSubs\]|\[720p\]).*(\[HorribleSubs\]|\[720p\])
    transmission:
      host: localhost
      port: 9091
      username: ""
      password: ""
      path: /media/Stronger/Plex/Series/Animes
  Filmes:
    sequence:
      - rss: https://yts.lt/rss/SOUL/all/all/0
      - rss: https://yts.lt/rss/Bad%Boys%For%Life/all/all/0
      - rss: https://yts.lt/rss/F9/all/all/0
      - rss: https://yts.lt/rss/Black%Widow/all/all/0
      - rss: https://yts.lt/rss/SOUL/all/all/0
      - rss: https://yts.lt/rss/Wonder%Woman%1984/all/all/0
    regexp:
      accept:
        - (BluRay|WEB|1080p).*(BluRay|WEB|1080p)
      reject:
        - (3D|720p)
    transmission:
      host: localhost
      port: 9091
      username: ""
      password: ""
      path: /media/Stronger/Plex/Filmes
  Series:
    sequence:
      - rss: https://showrss.info/show/651.rss
      - rss: https://showrss.info/show/1296.rss
      - rss: https://showrss.info/show/1283.rss
    regexp:
      accept:
        - (1080p)
      reject:
        - (Repack|PROPER)
    transmission:
      host: localhost
      port: 9091
      username: ""
      password: ""
      path: /media/Stronger/Plex/Series
